// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	frontend_auth "GoMall/app/frontend/biz/router/frontend_auth"
	frontend_home "GoMall/app/frontend/biz/router/frontend_home"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	frontend_auth.Register(r)

	frontend_home.Register(r)
}
